### ISSUE TITLE
securityError on Internet Explorer

### ISSUE THREAD

**Issue by moatasem1** [manuhg/unmin-coinhive#1]
Internet Explorer 11 shows this error

![error_screenshot](https://user-images.githubusercontent.com/22029917/39087670-a85d0ee0-45a4-11e8-9ca2-aa80ec3a8646.PNG)

**Comment by manuhg** [comment]
Well it is a malware! so i beleive thats why its happening

**Comment by moatasem1** [comment]
Is it working on IE on your device then?

On Saturday, April 28, 2018, Manu Hegde <notifications@github.com> wrote:
> Well it is a malware! so i beleive thats why its happening
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci3.googleusercontent.com/proxy/lDteZiEu8PftqtzJZdv4-wKmhx7diW9z_LehQlpMHmC3bio4FOXae2CJgx6YSwXV07aR1pwWDNR1XVVjlYufBdyUhGpZO9wmtcYeWFdkHcAHrFGFibVDRkf0YRtc_knTQph1Nnl9PoxkHLYrkhumGIhtoNDEHA=s0-d-e1-ft#https://github.com/notifications/beacon/AVAmXSxq0gAUBiopyNQD_dTipjIlIdPuks5ts_RSgaJpZM4TekcT.gif>

**Comment by manuhg** [comment]
it works on chrome and firefox. i dont use windows.
